#!/usr/bin/env bash
set -euo pipefail

# This script generates the storage layout for PDPVerifier
# It uses forge inspect to get the storage layout in a table format
# and then formats it into a Solidity file for tracking.

CONTRACT="PDPVerifier"
OUTPUT_FILE="src/${CONTRACT}ServiceLayout.sol"

echo "Generating storage layout for ${CONTRACT}..."

# Get storage layout from forge and parse the table format
LAYOUT_CONTENT=$(forge inspect ${CONTRACT} storage-layout | awk -F'|' '/src\/'${CONTRACT}'\.sol/ { gsub(/^[ \t]+|[ \t]+$/, "", $2); gsub(/^[ \t]+|[ \t]+$/, "", $3); gsub(/^[ \t]+|[ \t]+$/, "", $4); print "     * [slot: " $4 "] " $3 " " $2 }')

# Generate Solidity file
cat << SOL_EOF > "${OUTPUT_FILE}"
// SPDX-License-Identifier: Apache-2.0 OR MIT
pragma solidity ^0.8.20;

/**
 * @title ${CONTRACT}ServiceLayout
 * @notice This file defines the storage layout for ${CONTRACT}.
 * @dev This file is auto-generated by \`make gen\`. DO NOT EDIT MANUALLY.
 * This contract should NOT be deployed or used directly; it is only for storage slot tracking.
 */
abstract contract ${CONTRACT}ServiceLayout {
    /**
     * @dev STORAGE LAYOUT (slot: type name)
${LAYOUT_CONTENT}
     */
}
SOL_EOF

echo "Storage layout generated at ${OUTPUT_FILE}"
