// SPDX-License-Identifier: Apache-2.0 OR MIT
pragma solidity ^0.8.20;

/**
 * @title PDPVerifierServiceLayout
 * @notice This file defines the storage layout for PDPVerifier.
 * @dev This file is auto-generated by `make gen`. DO NOT EDIT MANUALLY.
 * This contract should NOT be deployed or used directly; it is only for storage slot tracking.
 */
abstract contract PDPVerifierServiceLayout {
    /**
     * @dev STORAGE LAYOUT (slot: type name)
     * [slot: 0] uint256 challengeFinality
     * [slot: 1] uint64 nextDataSetId
     * [slot: 2] mapping(uint256 => mapping(uint256 => struct Cids.Cid)) pieceCids
     * [slot: 3] mapping(uint256 => mapping(uint256 => uint256)) pieceLeafCounts
     * [slot: 4] mapping(uint256 => mapping(uint256 => uint256)) sumTreeCounts
     * [slot: 5] mapping(uint256 => uint256) nextPieceId
     * [slot: 6] mapping(uint256 => uint256) dataSetLeafCount
     * [slot: 7] mapping(uint256 => uint256) nextChallengeEpoch
     * [slot: 8] mapping(uint256 => address) dataSetListener
     * [slot: 9] mapping(uint256 => uint256) challengeRange
     * [slot: 10] mapping(uint256 => uint256[]) scheduledRemovals
     * [slot: 11] mapping(uint256 => mapping(uint256 => uint256)) scheduledRemovalsBitmap
     * [slot: 12] mapping(uint256 => address) storageProvider
     * [slot: 13] mapping(uint256 => address) dataSetProposedStorageProvider
     * [slot: 14] mapping(uint256 => uint256) dataSetLastProvenEpoch
     * [slot: 15] struct PDPVerifier.FeeStatus feeStatus
     * [slot: 16] struct PDPVerifier.PlannedUpgrade nextUpgrade
     */

    }
