name: Solidity Lint Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.7.1

      - name: Install Dependencies
        run: |
          forge install

      - name: fmt
        run: |
          forge fmt --check

      - name: lint
        run: |
          forge lint --deny notes --quiet
