name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: configure
        run: ./configure

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: |
          forge install

      - name: Run build
        run: |
          export PATH="/home/runner/.config/.foundry/bin:$PATH";
          make build;

      - name: Run tests
        run: |
          export PATH="/home/runner/.config/.foundry/bin:$PATH";
          make test;

      - name: Check storage layout
        run: |
          export PATH="/home/runner/.config/.foundry/bin:$PATH";
          make check-layout;
